In [1]:
import numpy as np

In [3]:
weights = np.around(np.random.uniform(size=6), decimals=2)
biases = np.around(np.random.uniform(size=3), decimals=2)

In [4]:
print(weights)
print(biases)

[0.99 0.69 0.56 0.24 0.79 0.58]
[0.11 0.76 0.34]


In [5]:
x_1 = 0.5 # input 1
x_2 = 0.85 # input 2

print('x1 is {} and x2 is {}'.format(x_1, x_2))

x1 is 0.5 and x2 is 0.85


In [6]:
z_11 = x_1 * weights[0] + x_2 * weights[2] + biases[0]

In [9]:
z_12 = x_1 * weights[2] + x_2 * weights[3] + biases[1]

In [10]:
print('The weighted sum of the inputs at the second node in the hidden layer is {}'.format(np.around(z_12, decimals=4)))

The weighted sum of the inputs at the second node in the hidden layer is 1.244


In [13]:
a_11 = 1/ (1+ np.exp(-z_11))
a_12 = 1/ (1+np.exp(-z_12))

In [14]:
z_2 = a_11 * weights[4] + a_12 * weights[5] + biases[2]

In [16]:
a_2 = 1/(1+np.exp(-z_2))

In [17]:
print('The output of the network for x1 = 0.5 and x2 = 0.85 is {}'.format(np.around(a_2, decimals=4)))

The output of the network for x1 = 0.5 and x2 = 0.85 is 0.799


In [18]:
n = 2
num_hidden_layers = 2
m = [2,2]
num_nodes_output = 1

In [28]:
num_nodes_previous = n
network = {}

for layer in range(num_hidden_layers + 1):
    if layer == num_hidden_layers:
        layer_name = 'output'
        num_nodes = num_nodes_output
    else:
        layer_name = 'layer_{}'.format(layer + 1)
        num_nodes = m[layer]
    
    network[layer_name] = {}
    for node in range(num_nodes):
        node_name = 'node_{}'.format(node+1)
        network[layer_name][node_name] = {
            'weights': np.around(np.random.uniform(size=num_nodes_previous),decimals=2),
            'bias': np.around(np.random.uniform(size=1),decimals=2)
            
        }
    num_nodes_previous = num_nodes
        

In [29]:
network
    
    

{'layer_1': {'node_1': {'weights': array([0.29, 0.37]), 'bias': array([0.84])},
  'node_2': {'weights': array([0.48, 0.5 ]), 'bias': array([0.8])}},
 'layer_2': {'node_1': {'weights': array([0.32, 0.03]), 'bias': array([0.21])},
  'node_2': {'weights': array([0.57, 0.79]), 'bias': array([0.06])}},
 'output': {'node_1': {'weights': array([0.79, 0.75]), 'bias': array([0.99])}}}

In [31]:
def initialize_network(num_inputs, num_hidden_layers, num_nodes_hidden, num_nodes_output):
    num_nodes_previous = num_inputs
    network = {}
    
    for layer in range(num_hidden_layers+1):
        if layer==num_hidden_layers:
            layer_name='output'
            num_nodes=num_nodes_output
        else:
            layer_name='layer_{}'.format(layer + 1)
            num_nodes = num_nodes_hidden[layer]
        
        network[layer_name]={}
        for node in range(num_nodes):
            node_name = 'node_{}'.format(node+1)
            network[layer_name][node_name] = {
                'weights': np.around(np.random.uniform(size=num_nodes_previous), decimals=2),
                'bias': np.around(np.random.uniform(size=1), decimals=2),
            }
    
        num_nodes_previous = num_nodes
        
    return network
            

In [33]:
initialize_network(5,3,[3,2,3],1)

{'layer_1': {'node_1': {'weights': array([0.2 , 0.66, 0.93, 0.04, 0.11]),
   'bias': array([0.53])},
  'node_2': {'weights': array([0.39, 0.29, 0.07, 0.15, 0.  ]),
   'bias': array([0.42])},
  'node_3': {'weights': array([0.05, 0.63, 0.35, 0.98, 0.15]),
   'bias': array([0.22])}},
 'layer_2': {'node_1': {'weights': array([0.44, 0.35, 0.42]),
   'bias': array([0.08])},
  'node_2': {'weights': array([0.01, 0.45, 0.51]), 'bias': array([0.14])}},
 'layer_3': {'node_1': {'weights': array([0.69, 0.97]), 'bias': array([0.87])},
  'node_2': {'weights': array([0.76, 0.68]), 'bias': array([0.12])},
  'node_3': {'weights': array([0.44, 0.52]), 'bias': array([0.42])}},
 'output': {'node_1': {'weights': array([0.19, 0.97, 0.77]),
   'bias': array([0.19])}}}

In [44]:
def compute_weighted_sum(inputs, weights, bias):
    return np.sum(inputs * weights) + bias

In [45]:
from random import seed

In [46]:
np.random.seed(12)
inputs = np.around(np.random.uniform(size=5), decimals=2)
print('The inputs to the network are {}'.format(inputs))

The inputs to the network are [0.15 0.74 0.26 0.53 0.01]


In [49]:
small_network = initialize_network(5, 3, [3, 2, 3], 1)

In [50]:
node_weights = small_network['layer_1']['node_1']['weights']
node_bias = small_network['layer_1']['node_1']['bias']
weighted_sum = compute_weighted_sum(inputs, node_weights, node_bias)
print('The weighted sum at the first node in the hidden layer is {}'.format(np.around(weighted_sum[0], decimals=4)))

The weighted sum at the first node in the hidden layer is 1.602


In [51]:
def node_activation(weighted_sum):
    return 1.0 / (1.0 + np.exp(-1 * weighted_sum))

In [52]:
node_output  = node_activation(compute_weighted_sum(inputs, node_weights, node_bias))
print('The output of the first node in the hidden layer is {}'.format(np.around(node_output[0], decimals=4)))

The output of the first node in the hidden layer is 0.8323


In [55]:
network['layer_1']['node_1']

{'weights': array([0.29, 0.37]), 'bias': array([0.84])}

In [58]:
def forward_propagate(network, inputs):
    
    layer_inputs = list(inputs) # start with the input layer as the input to the first hidden layer
    
    for layer in network:
        
        layer_data = network[layer]
        
        layer_outputs = [] 
        for layer_node in layer_data:
        
            node_data = layer_data[layer_node]
        
            # compute the weighted sum and the output of each node at the same time 
            node_output = node_activation(compute_weighted_sum(layer_inputs, node_data['weights'], node_data['bias']))
            layer_outputs.append(np.around(node_output[0], decimals=4))
            
        if layer != 'output':
            print('The outputs of the nodes in hidden layer number {} is {}'.format(layer.split('_')[1], layer_outputs))
    
        layer_inputs = layer_outputs # set the output of this layer to be the input to next layer

    network_predictions = layer_outputs
    return network_predictions

In [59]:
predictions = forward_propagate(small_network, inputs)
print('The predicted value by the network for the given input is {}'.format(np.around(predictions[0], decimals=4)))

The outputs of the nodes in hidden layer number 1 is [0.8323, 0.8268, 0.7735]
The outputs of the nodes in hidden layer number 2 is [0.7932, 0.8991]
The outputs of the nodes in hidden layer number 3 is [0.8232, 0.8924, 0.8141]
The predicted value by the network for the given input is 0.9112


In [60]:
inputs = np.around(np.random.uniform(size=5), decimals=2)
inputs

array([0.42, 0.42, 0.46, 0.37, 0.47])